### PR TITLE
TKNECO-30: Bootstrapping Project

### PR DESCRIPTION
**Pull request by otaviof**
Bootstrapping the basic project automation, testing and Helm Chart structure.

### CODE REVIEW

**Comment by otaviof** [comment]
> @otaviof just a doubt about the repo. In the Chart.yaml we have a generic name `task-container`, so for every task we are going to have its separate `values.yaml` and `task.yaml` (and `scipts?`)? Or every task will have its own branch?

We should have a single Chart for the whole repository, so a single `Chart.yaml` file.

**Comment by vdemeester** [comment]
@otaviof but they could be multiple task, right ?

**Comment by Senjuti256** [comment]
Whatever I could decipher from other repositories is that the Chart.yaml file contains all the necessary files and dependencies (other charts that need to be installed along with the main chart) to describe and install an application on Kubernetes. So will the dependencies, for each and every task, be incorporated in that single Chart.yaml file? Won't it create an issue if we try to run and check a few tasks only at any time and leave the others?

**Comment by Senjuti256** [comment]
Just a small query will we add the descriptions of all the tasks within the description of the Chart.yaml file?One more doubt I have what is the significance of | in the description? Everything else looks good to me?

**Review by Senjuti256 — COMMENTED** [review]
Everything looks good to me.

**Comment by otaviof** [comment]
> Just a small query will we add the descriptions of all the tasks within the description of the Chart.yaml file?One more doubt I have what is the significance of | in the description? Everything else looks good to me.

The pipe (`|`) on a YAML attributes create a block below it, so all the lines on that indentation level will be part of the attribute. We use this construction to create documentation blocks and things that may require multiple lines. For instance:

```yaml
some:
  attribute: |
    line 1
    line 2
    line 3
```

The value of this attribute is the following:

```text
line 1
line 2
line 3
```

In other words, we can emded a text snippet (or anything else for that matter), inside the YAML file.

**Review by vdemeester — APPROVED** [review]

**Pull request merged**
