### PR TITLE
Update params and readme for skopeo

### PR DESCRIPTION
**Pull request by savitaashture**

### CODE REVIEW

**Review by Senjuti256 — CHANGES_REQUESTED** [review]
These 2 lines need to be updated. @savitaashture

**Review by Senjuti256 — CHANGES_REQUESTED** [review]
` "params.SOURCE"
   "params.DESTINATION"`

These 2 lines (line 68 and 69 ) in task-skopeo-copy.yaml needs to be updated to 
` "params.SOURCE_IMAGE_URL"
   "params.DESTINATION_IMAGE_URL"`

**Comment by savitaashture** [comment]
> ` "params.SOURCE" "params.DESTINATION"`
> 
> These 2 lines (line 68 and 69 ) in task-skopeo-copy.yaml needs to be updated to ` "params.SOURCE_IMAGE_URL" "params.DESTINATION_IMAGE_URL"`

Done :+1:

**Review by Senjuti256 — APPROVED** [review]
LGTM

**Pull request merged**
